root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/site/server/"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "css"]
# Ignore these filename extensions or directories.
exclude_dir = ["cypress", "tmp", "node_modules"]
delay = 1000
send_interrupt = true

[proxy]
enabled = true
proxy_port = 3000
app_port = 8000

[log]
main_only = false
